config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  root 'pages#home'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  include Concerns::OmniauthConcern
  include Concerns::UserImagesConcern
  include Concerns::AuthenticationProvidersConcern

  belongs_to :user

  validates :user_id, :provider, :proid, presence: true

  def name
    return nil unless oauth_data
    oauth_data['name'].presence || "#{oauth_data['first_name']} #{oauth_data['last_name']}".strip.presence || nil
  end

  def display_name
    return nil unless oauth_data
    oauth_data['first_name'].presence || oauth_data['name'].presence ||
      oauth_data['nickname'].presence || username || oauth_data['username'].presence || nil
  end

  # Attempt to fill in oauth_data name fields for availabile data
  def populate_names
    return nil unless oauth_data.present?
    split_names = (name or '').split(' ')
    split_names.fill '', split_names.length..1
    oauth_data['first_name'] ||= split_names[0].presence or oauth_data['nickname'].presence or oauth_data['username'].presence
    oauth_data['last_name'] ||= split_names.drop(1).join(' ')
  end

  def profile_url
    oauth_data.try(:[], 'profile_url')
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource only: :destroy

  def index
    @failed = params[:failed]
    @return_to = user_authentications_path
    @authentications = @user.authentications.grouped_with_oauth
  end

  def destroy
    @authentication.destroy
    redirect_to user_authentications_path current_user
  end
end

app/views/authentications/_card.html.haml
- username = authentication.username_for_display or authentication.provider_name
- return_to ||= nil

= render layout: 'users/card', locals: {user: authentication, size: size, username: username, profile_url: authentication.profile_url, target: '_blank'} do
  .card__actions
    = link_to [current_user, authentication], data: {confirm: I18n.t('auth.destroy.prompt'), confirm_modal: disconnect_modal}, method: :delete, rel: 'tooltip', title: I18n.t('auth.destroy.tooltip') do
      %i.glyphicon.glyphicon-remove-circle
      = I18n.t('auth.destroy.link')
    = link_to provider_auth_path(authentication.provider, origin: return_to), data: {flow: 'connect'}, rel: 'tooltip', title: I18n.t('auth.reconnect.tooltip') do
      %i.glyphicon.glyphicon-repeat
      = I18n.t('auth.reconnect.link')

app/views/authentications/_debug_omniauth.html.haml
%p
  %strong
    Origin:
  %a{href: request.env['omniauth.origin']}
    = request.env['omniauth.origin']

%h2
  OAuth Response:

%p
  != ap request.env['omniauth.auth']

app/views/authentications/_providers.html.haml
- flow        ||= 'login'
- css_class   ||= 'btn btn-primary'
- providers   ||= Authentication.providers

.auth__providers
  - providers.each do |provider|
    .auth__providers__provider
      = link_to provider_auth_path(provider, flow: flow), data: {flow: flow, provider: provider}, class: css_class do
        %i.sico-fixed{class: "sico-#{provider}"}
        = Authentication.provider_name(provider)

app/views/authentications/failure.html.haml
-# Generic OAuth failure page
-# This page is displayed when it's not possible to show the error inline on another page
-# Test with /auth/failure

%h1 Ooops!
%p Something didn't work as expected. Please try again.

app/views/authentications/index.html.haml
#authentications-index.auth__form
  = render 'layouts/account_tabs'

  - if @failed
    = render 'auth/failed', provider: @provider

  - disconnect_modal_id = 'disconnect-oauth-modal'

  - Authentication.providers(:featured).each do |provider|
    .auth__group
      %h3
        %i.sico-fixed{class: "sico-#{provider}"}
        = Authentication.provider_name(provider)

      %ul
        - auths = @authentications[provider]
        - if auths.present?
          - auths.each do |authentication|
            %li
              = render 'authentications/card', authentication: authentication, size: :thumb, disconnect_modal: "##{disconnect_modal_id}", return_to: @return_to

        - if auths.blank? or Authentication.allow_multiple_for?(provider)
          %li
            - another = auths.present? ? 'Another ' : ''
            = link_to provider_auth_path(provider, origin: @return_to), class: 'btn btn-primary btn-sm', data: {flow: 'connect'} do
              %i{class: "sico-#{provider} sico-fixed"}
              Connect #{another}#{Authentication.provider_name(provider)}
            - if auths.present? && provider == 'twitter'
              .help-block
                You may need to first
                = link_to 'sign out of Twitter', Authentication.logout_url(:twitter), target: '_blank'

= render 'layouts/destroy_modal', id: disconnect_modal_id, i18n_prefix: 'auth.destroy'

- content_for :on_ready do
  $('#authentications-index [title]').tooltip({container: 'body', placement: 'bottom'})