config/routes.rb
# Route prefixes use a single letter to allow for vanity urls of two or more characters
Rails.application.routes.draw do
  if defined? Sidekiq
    require 'sidekiq/web'
    authenticate :user, lambda {|u| u.is_admin? } do
      mount Sidekiq::Web, at: '/admin/sidekiq/jobs', as: :sidekiq
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin' if defined? RailsAdmin

  # Static pages
  match '/error' => 'pages#error', via: [:get, :post], as: 'error_page'
  get '/terms' => 'pages#terms', as: 'terms'
  get '/privacy' => 'pages#privacy', as: 'privacy'

  # OAuth
  oauth_prefix = Rails.application.config.auth.omniauth.path_prefix
  get "#{oauth_prefix}/:provider/callback" => 'users/oauth#create'
  get "#{oauth_prefix}/failure" => 'users/oauth#failure'
  get "#{oauth_prefix}/:provider" => 'users/oauth#passthru', as: 'provider_auth'
  get oauth_prefix => redirect("#{oauth_prefix}/login")

  # Devise
  devise_prefix = Rails.application.config.auth.devise.path_prefix
  devise_for :users, path: devise_prefix,
    controllers: {registrations: 'users/registrations', sessions: 'users/sessions',
      passwords: 'users/passwords', confirmations: 'users/confirmations', unlocks: 'users/unlocks'},
    path_names: {sign_up: 'signup', sign_in: 'login', sign_out: 'logout'}
  devise_scope :user do
    get "#{devise_prefix}/after" => 'users/registrations#after_auth', as: 'user_root'
  end
  get devise_prefix => redirect('/a/signup')

  # User
  resources :users, path: 'u', only: :show do
    resources :authentications, path: 'accounts'
  end
  get '/home' => 'users#show', as: 'user_home'

  # Dummy preview pages for testing.
  get '/p/test' => 'pages#test', as: 'test'
  get '/p/email' => 'pages#email' if ENV['ALLOW_EMAIL_PREVIEW'].present?

  get 'robots.:format' => 'robots#index'

  root 'pages#home'
end

app/views/layouts/_account_tabs.html.haml
%ul.nav.nav-tabs
  %li{class: request.original_fullpath == edit_user_registration_path ? 'active' : ''}
    = link_to I18n.t('account.edit.link'), edit_user_registration_path
  %li{class: request.original_fullpath == user_authentications_path(current_user) ? 'active' : ''}
    = link_to I18n.t('auth.edit.link'), user_authentications_path(current_user)

app/views/layouts/_airbrake.html.haml
- if defined?(Airbrake) && Airbrake.configuration.js_api_key.present?
  = airbrake_javascript_notifier

app/views/layouts/_analytics.html.haml
- if Rails.application.config.analytics.google.id
  - content_for :on_ready do
    :plain
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', '#{Rails.application.config.analytics.google.id}']);
      _gaq.push(['_trackPageview']);
      $(document).on('page:change', function(){
        _gaq.push(['_trackPageview'])
      });

app/views/layouts/_destroy_modal.html.haml
- id ||= 'destroy-modal'
- i18n_prefix = i18n_prefix.present? ? "#{i18n_prefix}." : ''

.modal.fade{id: id, tabindex: -1, role: 'dialog', 'aria-labelledby' => "#{id}-title", 'aria-hidden' => true}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: 'modal'}, 'aria-hidden' => true} &times;
        %h4{id: "#{id}-title"}= I18n.t "#{i18n_prefix}prompt"
      .modal-body
        - warning = I18n.t "#{i18n_prefix}warning"
        - if warning.present?
          .alert.alert-danger
            %i.glyphicon.glyphicon-warning-sign.text-danger
            = warning
        %p= I18n.t "#{i18n_prefix}notice"
      .modal-footer
        %button.btn.btn-danger{data: {confirm: '', dismiss: 'modal'}}= I18n.t "#{i18n_prefix}submit"
        %button.btn.btn-default{data: {dismiss: 'modal'}}= I18n.t "#{i18n_prefix}cancel"

app/views/layouts/_footer.html.haml
%ul
  %li= link_to 'Terms', terms_path
  %li= link_to 'Privacy', privacy_path

app/views/layouts/_javascripts.html.haml
-# JavaScripts included in <body> for initializing Backbone views, etc.

-# Immediately executable javascript
- if content_for? :javascript
  = yield :javascript

-# Document ready javascript
- if content_for? :on_ready
  :javascript
    head.ready(function(){
      #{yield :on_ready}
    })

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String) and msg.present?
    - type = (['info', 'success', 'warning', 'danger'].include?(name.to_s) ? name : 'info')
    .alert.alert-dismissable{class: "alert-#{type}"}
      %button.close{'data-dismiss' => 'alert', 'aria-hidden' => true} &times;
      = msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
  .navbar-header
    %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-collapse'}}
      %span.sr-only
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to I18n.t('brand.name'), root_path, class: 'navbar-brand'

  .collapse.navbar-collapse
    %ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        %li.dropdown
          %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
            = render 'users/avatar', size: :tiny
            %b.caret
          %ul.dropdown-menu
            - if current_user.is_admin?
              %li= link_to I18n.t('admin.link'), rails_admin_path, data: {"no-turbolink" => true}
            %li= link_to I18n.t('account.edit.link'), edit_user_registration_path
            %li= link_to I18n.t('auth.logout.link'), destroy_user_session_path, rel: :nofollow
      - unless user_signed_in?
        %li= link_to I18n.t('auth.signup.link'), new_user_registration_path
        %li= link_to I18n.t('auth.login.link'), new_user_session_path

app/views/layouts/application.html.haml
!!!
%html.no-js{lang: 'en'}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
    %title= content_for?(:title) ? yield(:title) : I18n.t('brand.name')
    %meta{content: (content_for?(:description) ? yield(:description) : I18n.t('brand.name')), name: 'description'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    /[if lt IE 9]
      = javascript_include_tag 'ie', 'data-turbolinks-track' => true
    = javascript_include_tag 'head', 'data-turbolinks-track' => true
    = headjs_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield :head
    = render 'layouts/airbrake'
  %body{class: "controller__#{controller_name} action__#{action_name}"}
    = render 'layouts/navigation'
    .container
      .errors__container
        = render 'layouts/messages'
      = yield
      %footer.page__footer
        - if content_for? :footer
          = yield :footer
        - else
          = render 'layouts/footer'
    = render 'layouts/analytics'
    = render 'layouts/javascripts'

app/views/layouts/uncaught_error.js.haml
:plain
  var $wrap = $('.errors__container').empty()
  $wrap.append('#{escape_javascript(render 'layouts/messages')}')
  if ($wrap.length && typeof $.scrollTo == 'function') {
    $.scrollTo($wrap.offset().top - parseInt($('body').css('padding-top')), 300)
  }